#!/usr/bin/env python

# This program generates HTML presentations based in reveal.js, from a certain
# custom input format.

import argparse
import re
import sys
import urllib2
import StringIO
import os
import hashlib # For turning URLs into well-behaved filenames.
import time
import subprocess
import mimetypes
import shutil

import datgysylltu
import hunangynhwysol

from common import complain, get_file, to_from, mkdir_if_needed, download_if_needed


if __name__ == '__main__':
  main()
